services:
  app:
    build: .
    container_name: imago-challenge
    volumes:
      - analytics-data:/app/data
    restart: unless-stopped
    networks:
      - velez-network

volumes:
  analytics-data:

networks:
  velez-network:
    external: true
